export const HOME_COPY = {
  en: {
    descriptor: 'Korean-born artist based in Avignon, France',
    menu: {
      works: 'Works',
      exhibitions: 'Exhibitions',
      biography: 'Biography',
      critics: 'Critics',
      publications: 'Publications',
      contact: 'Contact',
    },
    scroll: 'Scroll to enter',
    museum: {
      aout: {
        title: 'August',
        medium: 'Mixed media',
      },
      twin: {
        title: 'Twin but Twin V',
        medium: 'Ash & mixed media',
      },
      tears: {
        title: 'Tears in the Ocean and the Sky',
        medium: 'Ash & mixed media on canvas',
      },
    },
    statementEyebrow: 'The practice',
    statement:
      'Working with ash, memory and light, Francesca Cho transforms traces of loss into enduring images of hope.',
    viewWork: 'View work',
    viewAllWorks: 'View all works',
    exhibitionEyebrow: 'Latest exhibition',
    exhibitionTitle: 'Confluence',
    exhibitionDate: '04—18 July 2026',
    exhibitionPlace: 'Atelier Galerie FCW · Avignon',
    exhibitionBody:
      'Three artists brought Korean and French perspectives together during the Festival d’Avignon, marking 140 years of diplomatic relations between France and Korea.',
    explore: 'Explore exhibition',
    quote: 'Hope is the flame that will never be extinguished.',
    quoteBy: 'Tabish Khan · London art critic, 2025',
    biographyEyebrow: 'A life between places',
    biographyTitle:
      'From Korea to London, and from London to the light of southern France.',
    biographyBody:
      'Her practice has travelled through painting, site-specific installation and performance, while returning to a singular material language of ash, remembrance and peace.',
    biographyCta: 'Discover the biography',
    pressEyebrow: 'Selected institutions',
    contactEyebrow: 'Inquiries',
    contactTitle: 'Begin a conversation',
    contactBody:
      'For exhibitions, curatorial projects, press and enquiries about available works.',
    formName: 'Name',
    formEmail: 'Email',
    formSubject: 'Subject',
    formSubjectPlaceholder: 'Select an inquiry',
    formSubjectExhibition: 'Exhibition or curatorial project',
    formSubjectArtwork: 'Available works',
    formSubjectPress: 'Press',
    formSubjectOther: 'Other',
    formMessage: 'Message',
    formSubmit: 'Send inquiry',
    visitLabel: 'Visit the gallery',
    followLabel: 'Follow',
    directionsLabel: 'Get directions',
  },
  fr: {
    descriptor: 'Artiste d’origine coréenne basée à Avignon, France',
    menu: {
      works: 'Œuvres',
      exhibitions: 'Expositions',
      biography: 'Biographie',
      critics: 'Critiques',
      publications: 'Publications',
      contact: 'Contact',
    },
    scroll: 'Faire défiler pour entrer',
    museum: {
      aout: {
        title: 'Août',
        medium: 'Techniques mixtes',
      },
      twin: {
        title: 'Jumeaux mais jumeaux V',
        medium: 'Cendre et techniques mixtes',
      },
      tears: {
        title: 'Larmes dans l’océan et le ciel',
        medium: 'Cendre et techniques mixtes sur toile',
      },
    },
    statementEyebrow: 'La pratique',
    statement:
      'À travers la cendre, la mémoire et la lumière, Francesca Cho transforme les traces de la perte en images durables d’espoir.',
    viewWork: 'Voir l’œuvre',
    viewAllWorks: 'Voir toutes les œuvres',
    exhibitionEyebrow: 'Dernière exposition',
    exhibitionTitle: 'Confluence',
    exhibitionDate: '04—18 juillet 2026',
    exhibitionPlace: 'Atelier Galerie FCW · Avignon',
    exhibitionBody:
      'Trois artistes ont réuni des regards coréens et français pendant le Festival d’Avignon, à l’occasion des 140 ans des relations diplomatiques entre la France et la Corée.',
    explore: 'Découvrir l’exposition',
    quote: 'L’espoir est la flamme qui ne s’éteindra jamais.',
    quoteBy: 'Tabish Khan · Critique d’art londonien, 2025',
    biographyEyebrow: 'Une vie entre plusieurs lieux',
    biographyTitle:
      'De la Corée à Londres, puis de Londres à la lumière du sud de la France.',
    biographyBody:
      'Sa pratique traverse la peinture, l’installation in situ et la performance, tout en revenant à un langage singulier fait de cendre, de mémoire et de paix.',
    biographyCta: 'Découvrir la biographie',
    pressEyebrow: 'Institutions sélectionnées',
    contactEyebrow: 'Demandes',
    contactTitle: 'Commencer une conversation',
    contactBody:
      'Pour les expositions, projets curatoriaux, la presse et les demandes concernant les œuvres disponibles.',
    formName: 'Nom',
    formEmail: 'E-mail',
    formSubject: 'Objet',
    formSubjectPlaceholder: 'Choisir une demande',
    formSubjectExhibition: 'Exposition ou projet curatorial',
    formSubjectArtwork: 'Œuvres disponibles',
    formSubjectPress: 'Presse',
    formSubjectOther: 'Autre',
    formMessage: 'Message',
    formSubmit: 'Envoyer',
    visitLabel: 'Visiter la galerie',
    followLabel: 'Suivre',
    directionsLabel: 'Itinéraire',
  },
  ko: {
    descriptor: '프랑스 아비뇽을 기반으로 활동하는 한국 출신 작가',
    menu: {
      works: '작품',
      exhibitions: '전시',
      biography: '작가 소개',
      critics: '비평',
      publications: '출판',
      contact: '문의',
    },
    scroll: '스크롤하여 들어가기',
    museum: {
      aout: {
        title: '8월',
        medium: '혼합 매체',
      },
      twin: {
        title: '쌍둥이지만 쌍둥이 V',
        medium: '재와 혼합 매체',
      },
      tears: {
        title: '바다와 하늘의 눈물',
        medium: '캔버스에 재와 혼합 매체',
      },
    },
    statementEyebrow: '작업 세계',
    statement:
      '조 프란체스카는 재, 기억, 빛을 통해 상실의 흔적을 오래 지속되는 희망의 이미지로 변환합니다.',
    viewWork: '작품 보기',
    viewAllWorks: '모든 작품 보기',
    exhibitionEyebrow: '최근 전시',
    exhibitionTitle: 'Confluence',
    exhibitionDate: '2026년 7월 4일—18일',
    exhibitionPlace: 'Atelier Galerie FCW · Avignon',
    exhibitionBody:
      '프랑스와 한국의 수교 140주년을 기념하여 세 명의 작가가 아비뇽 페스티벌 기간 동안 한국과 프랑스의 시선을 한자리에 모았습니다.',
    explore: '전시 보기',
    quote: '희망은 결코 꺼지지 않는 불꽃이다.',
    quoteBy: 'Tabish Khan · 런던 미술 평론가, 2025',
    biographyEyebrow: '장소를 잇는 삶',
    biographyTitle:
      '한국에서 런던으로, 그리고 런던에서 프랑스 남부의 빛으로.',
    biographyBody:
      '그의 작업은 회화, 장소 특정적 설치, 퍼포먼스를 가로지르며 재와 기억, 평화라는 고유한 물질 언어로 되돌아옵니다.',
    biographyCta: '작가 소개 보기',
    pressEyebrow: '주요 기관',
    contactEyebrow: '문의',
    contactTitle: '대화를 시작하세요',
    contactBody:
      '전시, 큐레토리얼 프로젝트, 언론 및 작품 문의를 위한 연락처입니다.',
    formName: '이름',
    formEmail: '이메일',
    formSubject: '문의 유형',
    formSubjectPlaceholder: '문의 유형을 선택하세요',
    formSubjectExhibition: '전시 및 큐레이토리얼 프로젝트',
    formSubjectArtwork: '구매 가능한 작품',
    formSubjectPress: '언론',
    formSubjectOther: '기타',
    formMessage: '메시지',
    formSubmit: '문의 보내기',
    visitLabel: '갤러리 방문',
    followLabel: '팔로우',
    directionsLabel: '길찾기',
  },
} as const;
